services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - OPA_URL=http://opa:8181/v1/data/rbac/allow
    depends_on:
      - opa

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8182:8181"
    volumes:
      - ./policies:/policies
    command:
      - "run"
      - "--server"
      - "/policies/rbac.rego"
